### ISSUE TITLE
Youtube link to GIF

### ISSUE THREAD

**Issue by ppth0608** [bigstark/animated-ratingbar#1]
데모 영상을 Youtube 링크 대신에 GIF를 사용해서 Readme에 표현하는건 어떠신가요?ㅎㅎㅎ
저는 [GIPHY Capture](https://itunes.apple.com/kr/app/giphy-capture.-the-gif-maker/id668208984?mt=12) 요거 사용해서 GIF 만듭니다!

**Comment by bigstark** [comment]
변경 완료했습니다 :)

Issue Close 하겠습니다.
